import React, { useState } from 'react';
import {
  X,
  GitPullRequest,
  GitBranch,
  GitCommit,
  CheckCircle2,
  AlertTriangle,
  Code2,
  Download,
  ExternalLink,
  Sparkles,
  Zap,
  ShieldCheck,
  FileCode,
  FolderGit2,
  Check,
} from 'lucide-react';
import { Language, GitHubFixPatch, FullAuditReport } from '../types';
import confetti from 'canvas-confetti';

interface GitHubAutoFixModalProps {
  isOpen: boolean;
  onClose: () => void;
  lang: Language;
  report?: FullAuditReport | null;
}

const DEFAULT_FIX_PATCHES: GitHubFixPatch[] = [
  {
    id: 'patch-security-headers',
    file: 'nginx.conf / _headers',
    category: 'security',
    title: 'HSTS, CSP & Security Headers Injection',
    titleTe: 'HSTS, CSP మరియు సెక్యూరిటీ హెడర్స్ కోడ్ ప్యాచ్',
    diffSummary: 'Injects Strict-Transport-Security, X-Content-Type-Options: nosniff, and Content-Security-Policy',
    diffCode: `+ # Strict Security Headers Auto-Generated by WebsiteHealth.AI
+ add_header Strict-Transport-Security "max-age=63072000; includeSubDomains; preload" always;
+ add_header X-Content-Type-Options "nosniff" always;
+ add_header X-Frame-Options "SAMEORIGIN" always;
+ add_header Referrer-Policy "strict-origin-when-cross-origin" always;
+ add_header Permissions-Policy "camera=(), microphone=(), geolocation=()" always;`,
    selected: true,
    linesAdded: 6,
    linesRemoved: 0,
  },
  {
    id: 'patch-jsonld-schema',
    file: 'src/components/SEOHead.tsx / index.html',
    category: 'seo',
    title: 'Organization, Website & Breadcrumbs JSON-LD',
    titleTe: 'ఆర్గనైజేషన్ & బ్రెడ్‌క్రంబ్స్ JSON-LD స్కీమా',
    diffSummary: 'Adds structured linked data for Google Rich Results & ChatGPT knowledge graphs',
    diffCode: `+ <script type="application/ld+json">
+ {
+   "@context": "https://schema.org",
+   "@type": "WebSite",
+   "name": "Target Website",
+   "url": "https://target-site.com",
+   "potentialAction": {
+     "@type": "SearchAction",
+     "target": "https://target-site.com/search?q={search_term_string}",
+     "query-input": "required name=search_term_string"
+   }
+ }
+ </script>`,
    selected: true,
    linesAdded: 12,
    linesRemoved: 0,
  },
  {
    id: 'patch-webp-compression',
    file: 'next.config.js / vite.config.ts',
    category: 'performance',
    title: 'Next-Gen WebP/AVIF Image Pipeline',
    titleTe: 'WebP మరియు AVIF ఇమేజ్ కంప్రెషన్ పైప్‌లైన్',
    diffSummary: 'Configures automated modern image format conversions saving ~65% image payload',
    diffCode: `module.exports = {
   images: {
-    formats: ['image/jpeg', 'image/png'],
+    formats: ['image/avif', 'image/webp'],
+    minimumCacheTTL: 31536000,
+    deviceSizes: [640, 750, 828, 1080, 1200, 1920],
   },
 };`,
    selected: true,
    linesAdded: 4,
    linesRemoved: 1,
  },
  {
    id: 'patch-dns-preconnect',
    file: 'public/index.html',
    category: 'performance',
    title: 'DNS Preconnect & Font Display Swap',
    titleTe: 'DNS ప్రీకనెక్ట్ మరియు ఫాంట్ డిస్‌ప్లే స్వాప్',
    diffSummary: 'Eliminates 320ms render-blocking stylesheet latency for Google Fonts',
    diffCode: `+ <link rel="preconnect" href="https://fonts.googleapis.com" crossorigin />
+ <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
+ <link rel="preload" as="style" href="https://fonts.googleapis.com/css2?display=swap" />`,
    selected: true,
    linesAdded: 3,
    linesRemoved: 0,
  },
  {
    id: 'patch-viewport-contrast',
    file: 'src/styles/globals.css',
    category: 'accessibility',
    title: 'WCAG 2.1 AA Contrast & Focus States',
    titleTe: 'WCAG 2.1 కాంట్రాస్ట్ మరియు ఫోకస్ రింగ్స్ ఫిక్స్',
    diffSummary: 'Guarantees 4.5:1 text color contrast and keyboard navigation rings',
    diffCode: `+ /* Accessible Keyboard Navigation Focus Indicator */
+ :focus-visible {
+   outline: 2px solid #6366f1 !important;
+   outline-offset: 2px !important;
+ }`,
    selected: false,
    linesAdded: 4,
    linesRemoved: 0,
  },
];

export const GitHubAutoFixModal: React.FC<GitHubAutoFixModalProps> = ({
  isOpen,
  onClose,
  lang,
  report,
}) => {
  const isTe = lang === 'te';
  const targetUrl = report?.url || 'https://mywebsite.com';

  const [repoUrl, setRepoUrl] = useState<string>('https://github.com/my-org/my-website');
  const [branchName, setBranchName] = useState<string>('ai-fix/website-health-optimization');
  const [baseBranch, setBaseBranch] = useState<string>('main');
  const [patches, setPatches] = useState<GitHubFixPatch[]>(DEFAULT_FIX_PATCHES);
  const [selectedProvider, setSelectedProvider] = useState<'github' | 'gitlab' | 'bitbucket'>('github');
  const [isCreatingPr, setIsCreatingPr] = useState<boolean>(false);
  const [createdPrResult, setCreatedPrResult] = useState<{
    prUrl: string;
    prNumber: number;
    branch: string;
  } | null>(null);

  if (!isOpen) return null;

  const togglePatch = (id: string) => {
    setPatches((prev) =>
      prev.map((p) => (p.id === id ? { ...p, selected: !p.selected } : p))
    );
  };

  const handleSelectAll = () => {
    setPatches((prev) => prev.map((p) => ({ ...p, selected: true })));
  };

  const selectedCount = patches.filter((p) => p.selected).length;
  const totalLinesAdded = patches
    .filter((p) => p.selected)
    .reduce((sum, p) => sum + p.linesAdded, 0);

  const handleCreatePullRequest = () => {
    if (selectedCount === 0) {
      alert(isTe ? 'దయచేసి కనీసం ఒక ప్యాచ్‌ని ఎంచుకోండి' : 'Please select at least one fix patch');
      return;
    }

    setIsCreatingPr(true);
    setTimeout(() => {
      const prNumber = Math.floor(Math.random() * 40) + 120;
      setCreatedPrResult({
        prUrl: `${repoUrl}/pull/${prNumber}`,
        prNumber,
        branch: branchName,
      });
      setIsCreatingPr(false);
      confetti({ particleCount: 50, spread: 70, origin: { y: 0.6 } });
    }, 1400);
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-3 sm:p-4 bg-slate-950/80 backdrop-blur-md overflow-y-auto">
      <div
        id="github-autofix-modal"
        className="relative w-full max-w-4xl bg-slate-900 border border-slate-800 rounded-3xl shadow-2xl overflow-hidden my-6 max-h-[92vh] flex flex-col"
      >
        {/* Header */}
        <div className="flex items-center justify-between px-6 py-4 border-b border-slate-800 bg-slate-900/90 sticky top-0 z-20">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 rounded-2xl bg-indigo-500/10 border border-indigo-500/30 flex items-center justify-center text-indigo-400">
              <FolderGit2 className="w-5 h-5" />
            </div>
            <div>
              <div className="flex items-center gap-2">
                <h2 className="text-base sm:text-lg font-black text-white tracking-tight">
                  {isTe
                    ? '1-క్లిక్ GitHub ఆటో-ఫిక్స్ Pull Request ఇంజిన్'
                    : '1-Click GitHub Auto-Fix Pull Request Engine'}
                </h2>
                <span className="text-[10px] font-mono font-bold uppercase tracking-wider px-2 py-0.5 rounded-full bg-indigo-500/20 text-indigo-300 border border-indigo-500/30 flex items-center gap-1">
                  <GitPullRequest className="w-3 h-3 text-indigo-400" />
                  <span>CI/CD Automated</span>
                </span>
              </div>
              <p className="text-xs text-slate-400">
                {isTe
                  ? 'మీ కోడ్ రిపోజిటరీకి AI స్వయంగా కోడ్ ఫిక్స్‌లతో సిద్ధం చేసిన Pull Request ని నేరుగా పంపుతుంది'
                  : 'Automatically generate and open verified pull requests with clean diffs for your repository'}
              </p>
            </div>
          </div>
          <button
            onClick={onClose}
            aria-label="Close"
            className="w-9 h-9 rounded-xl bg-slate-800 hover:bg-slate-700 text-slate-400 hover:text-white flex items-center justify-center transition-colors cursor-pointer"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Body */}
        <div className="flex-1 overflow-y-auto p-6 space-y-6">
          {createdPrResult ? (
            /* Success State */
            <div className="p-8 rounded-3xl bg-emerald-950/30 border-2 border-emerald-500/50 text-center space-y-4 animate-fadeIn">
              <div className="w-16 h-16 rounded-full bg-emerald-500/20 border border-emerald-500/40 flex items-center justify-center text-emerald-400 mx-auto">
                <CheckCircle2 className="w-8 h-8" />
              </div>
              <div className="space-y-1">
                <h3 className="text-xl font-black text-white">
                  {isTe ? 'Pull Request విజయవంతంగా క్రియేట్ చేయబడింది!' : 'Pull Request Successfully Created!'}
                </h3>
                <p className="text-xs text-slate-300 max-w-lg mx-auto">
                  {isTe
                    ? `మీ బ్రాంచ్ ${createdPrResult.branch} లో ${selectedCount} ప్యాచ్‌లు కమిట్ చేయబడ్డాయి. మీరు ఇప్పుడే GitHub లో రివ్యూ చేసి మెర్జ్ చేసుకోవచ్చు.`
                    : `Committed ${selectedCount} verified fixes into branch ${createdPrResult.branch}. Ready for 1-click merge!`}
                </p>
              </div>

              <div className="p-4 rounded-2xl bg-slate-950 border border-slate-800 inline-flex items-center gap-3 font-mono text-xs text-indigo-300">
                <GitPullRequest className="w-4 h-4 text-emerald-400" />
                <span>PR #{createdPrResult.prNumber}: feat(audit): automated website health remediation</span>
              </div>

              <div className="flex items-center justify-center gap-3 pt-2">
                <button
                  onClick={() => setCreatedPrResult(null)}
                  className="px-4 py-2.5 rounded-xl bg-slate-800 hover:bg-slate-700 text-white text-xs font-bold transition-colors cursor-pointer"
                >
                  {isTe ? 'మరో PR క్రియేట్ చేయండి' : 'Create Another PR'}
                </button>
                <a
                  href={`#`}
                  onClick={(e) => {
                    e.preventDefault();
                    alert(isTe ? 'GitHub లో PR ఓపెన్ చేయబడింది!' : 'Mock PR opened in new tab!');
                  }}
                  className="px-5 py-2.5 rounded-xl bg-emerald-500 hover:bg-emerald-400 text-slate-950 font-black text-xs flex items-center gap-1.5 shadow-lg shadow-emerald-500/20 transition-all cursor-pointer"
                >
                  <span>{isTe ? 'GitHub లో PR చూడండి' : 'View on GitHub'}</span>
                  <ExternalLink className="w-3.5 h-3.5" />
                </a>
              </div>
            </div>
          ) : (
            <>
              {/* Repository & Branch Selector */}
              <div className="p-4 rounded-2xl bg-slate-950 border border-slate-800 space-y-4">
                <div className="flex items-center justify-between flex-wrap gap-2">
                  <span className="text-xs font-bold text-slate-300 uppercase tracking-wider">
                    {isTe ? 'రిపోజిటరీ కనెక్షన్ (Git Provider)' : 'Git Provider & Repository Target'}
                  </span>
                  <div className="flex items-center gap-1.5">
                    {(['github', 'gitlab', 'bitbucket'] as const).map((p) => (
                      <button
                        key={p}
                        onClick={() => setSelectedProvider(p)}
                        className={`px-3 py-1 rounded-lg text-[11px] font-mono font-bold capitalize transition-all border ${
                          selectedProvider === p
                            ? 'bg-indigo-500 text-white border-indigo-400'
                            : 'bg-slate-900 text-slate-400 border-slate-800 hover:text-white'
                        }`}
                      >
                        {p}
                      </button>
                    ))}
                  </div>
                </div>

                <div className="grid grid-cols-1 sm:grid-cols-3 gap-3">
                  <div className="sm:col-span-2 space-y-1">
                    <label className="text-[11px] text-slate-400 font-mono">Repository URL</label>
                    <input
                      type="text"
                      value={repoUrl}
                      onChange={(e) => setRepoUrl(e.target.value)}
                      className="w-full px-3 py-2 bg-slate-900 border border-slate-700 rounded-xl text-xs font-mono text-white focus:border-indigo-400 focus:outline-none"
                    />
                  </div>
                  <div className="space-y-1">
                    <label className="text-[11px] text-slate-400 font-mono">Base Branch</label>
                    <input
                      type="text"
                      value={baseBranch}
                      onChange={(e) => setBaseBranch(e.target.value)}
                      className="w-full px-3 py-2 bg-slate-900 border border-slate-700 rounded-xl text-xs font-mono text-white focus:border-indigo-400 focus:outline-none"
                    />
                  </div>
                </div>
              </div>

              {/* Patches Selection & Code Diff Preview */}
              <div className="space-y-3">
                <div className="flex items-center justify-between">
                  <h4 className="text-xs font-bold uppercase tracking-wider text-slate-300 flex items-center gap-2">
                    <Code2 className="w-4 h-4 text-indigo-400" />
                    <span>
                      {isTe
                        ? `ఎంచుకున్న కోడ్ ప్యాచ్‌లు (${selectedCount}/${patches.length})`
                        : `Selected Remediation Patches (${selectedCount}/${patches.length})`}
                    </span>
                  </h4>
                  <button
                    onClick={handleSelectAll}
                    className="text-xs text-indigo-400 hover:text-indigo-300 font-bold cursor-pointer"
                  >
                    {isTe ? 'అన్నీ ఎంచుకోండి' : 'Select All Patches'}
                  </button>
                </div>

                <div className="space-y-3">
                  {patches.map((patch) => (
                    <div
                      key={patch.id}
                      className={`p-4 rounded-2xl border transition-all ${
                        patch.selected
                          ? 'bg-slate-950/90 border-indigo-500/40 shadow-sm'
                          : 'bg-slate-950/40 border-slate-800 opacity-60'
                      }`}
                    >
                      <div className="flex items-start justify-between gap-3 mb-2">
                        <div
                          onClick={() => togglePatch(patch.id)}
                          className="flex items-start gap-3 cursor-pointer select-none"
                        >
                          <div
                            className={`w-5 h-5 rounded-lg mt-0.5 flex items-center justify-center border transition-colors ${
                              patch.selected
                                ? 'bg-indigo-500 border-indigo-400 text-white'
                                : 'border-slate-700 bg-slate-900 text-transparent'
                            }`}
                          >
                            <Check className="w-3.5 h-3.5 stroke-[3]" />
                          </div>
                          <div>
                            <div className="text-xs sm:text-sm font-bold text-white flex items-center gap-2">
                              <span>{isTe ? patch.titleTe : patch.title}</span>
                              <span className="text-[10px] font-mono uppercase px-2 py-0.5 rounded-full bg-slate-800 text-slate-300 border border-slate-700">
                                {patch.file}
                              </span>
                            </div>
                            <p className="text-[11px] text-slate-400 mt-0.5">{patch.diffSummary}</p>
                          </div>
                        </div>

                        <span className="text-[11px] font-mono text-emerald-400 font-bold shrink-0">
                          +{patch.linesAdded} lines
                        </span>
                      </div>

                      {/* Code Diff Box */}
                      {patch.selected && (
                        <div className="mt-3 p-3 rounded-xl bg-slate-900 border border-slate-800 font-mono text-[11px] text-slate-300 overflow-x-auto leading-relaxed whitespace-pre">
                          {patch.diffCode}
                        </div>
                      )}
                    </div>
                  ))}
                </div>
              </div>
            </>
          )}
        </div>

        {/* Footer Actions */}
        {!createdPrResult && (
          <div className="p-4 sm:p-5 border-t border-slate-800 bg-slate-950/90 flex flex-col sm:flex-row items-center justify-between gap-3">
            <span className="text-xs text-slate-400 font-mono">
              Total {totalLinesAdded} lines across {selectedCount} file diffs
            </span>

            <button
              onClick={handleCreatePullRequest}
              disabled={isCreatingPr || selectedCount === 0}
              className="w-full sm:w-auto px-6 py-3 bg-gradient-to-r from-indigo-500 via-purple-500 to-pink-500 hover:from-indigo-400 hover:to-pink-400 text-white font-black text-xs sm:text-sm rounded-xl shadow-lg shadow-indigo-500/20 flex items-center justify-center gap-2 cursor-pointer transition-all hover:scale-[1.02] active:scale-95 disabled:opacity-50"
            >
              <GitPullRequest className={`w-4 h-4 ${isCreatingPr ? 'animate-spin' : ''}`} />
              <span>
                {isCreatingPr
                  ? 'Generating Commits & Opening PR...'
                  : isTe
                  ? '1-క్లిక్ ఆటో-ఫిక్స్ PR సృష్టించండి'
                  : 'Open 1-Click Auto-Fix Pull Request'}
              </span>
            </button>
          </div>
        )}
      </div>
    </div>
  );
};
